name: GitHub Actions Demo
on: [push]
jobs:
  Glue-CICD-Workflow:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      
      - name: Configure AWS credentials from development account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::754915207637:role/AWSGlueServiceRoleDefault
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_GLUE_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_GLUE_DEV_SECRET_ACCESS_KEY }}
